More fixes and updates
CrowdStrike/cicd-falcon-tutorial pull request #8
Opened 2021-03-10 21:18 UTC by redhatrises

- More pep8 fixes
- Add env variables handling
- Add some defaults for cli args
- Add support for older docker py API

2021-03-10 21:23 UTC, shawndwells requested changes

2021-03-10 21:23 UTC, shawndwells commented on cs_scanimage.py
> +        description='Crowdstrike - scan your Docker image.')
```suggestion
        description='Crowdstrike - scan your container image.')
```

2021-03-10 22:30 UTC, redhatrises commented
@isimluk thoughts?

2021-03-10 22:33 UTC, isimluk commented
Would you be willing to use FALCON_CLIENT_ID, FALCON_CLIENT_SECRET, and FALCON_CLOUD as environment variables?

I am trying to get us towards some consistency, so I always use these 3 names.

2021-03-10 22:34 UTC, isimluk approved these changes
👍 LGTM, like the direction!

2021-03-10 22:38 UTC, redhatrises commented
> Would you be willing to use FALCON_CLIENT_ID, FALCON_CLIENT_SECRET, and FALCON_CLOUD as environment variables?
> 
> I am trying to get us towards some consistency, so I always use these 3 names.

Works for me... I just hate typing those in... that's all. :D

2021-03-10 22:43 UTC, redhatrises commented
> > Would you be willing to use FALCON_CLIENT_ID, FALCON_CLIENT_SECRET, and FALCON_CLOUD as environment variables?
> > I am trying to get us towards some consistency, so I always use these 3 names.
> 
> Works for me... I just hate typing those in... that's all. :D

Updated the variables. Failing tests can be ignored until we can determine the best fixes for them.

2021-03-11 16:33 UTC, isimluk commented
LGTM. 👍 💯

2021-03-11 16:34 UTC, merged

2021-03-11 16:34 UTC, redhatrises commented
Thanks @isimluk !